sudo: false
language: node_js
node_js:
  - 14
cache: npm
install:
  npm install
  yarn install
branches:
  only:
    - main # build master branch onl
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public